["8:118"]
alive_cells = [ [ 5, 10,], [ 5, 11,], [ 7, 7,], [ 4, 8,], [ 5, 8,], [ 11, 13,], [ 5, 9,], [ 17, 3,],]
["9:104"]
alive_cells = [ [ 9, 10,], [ 5, 15,], [ 10, 14,], [ 3, 1,], [ 11, 13,], [ 12, 13,], [ 0, 5,], [ 9, 11,], [ 10, 12,],]
["10:110"]
alive_cells = [ [ 1, 2,], [ 2, 1,], [ 6, 5,], [ 3, 1,], [ 6, 4,], [ 4, 18,], [ 1, 0,], [ 8, 18,], [ 6, 3,], [ 14, 5,],]
["8:100"]
alive_cells = [ [ 12, 17,], [ 16, 15,], [ 13, 17,], [ 16, 16,], [ 14, 17,], [ 2, 15,], [ 9, 9,], [ 13, 16,],]
["10:107"]
alive_cells = [ [ 8, 4,], [ 9, 19,], [ 10, 4,], [ 5, 4,], [ 9, 2,], [ 9, 5,], [ 0, 2,], [ 17, 15,], [ 12, 11,], [ 9, 4,],]
["7:105"]
alive_cells = [ [ 18, 4,], [ 3, 1,], [ 1, 4,], [ 1, 0,], [ 3, 3,], [ 5, 3,], [ 3, 2,],]
["10:114"]
alive_cells = [ [ 13, 4,], [ 7, 1,], [ 1, 11,], [ 12, 10,], [ 3, 10,], [ 14, 10,], [ 19, 0,], [ 3, 12,], [ 4, 11,], [ 3, 11,],]
