["8:118"]
alive_cells = [ [ 5, 10,], [ 5, 11,], [ 7, 7,], [ 4, 8,], [ 5, 8,], [ 11, 13,], [ 5, 9,], [ 17, 3,],]
["9:104"]
alive_cells = [ [ 9, 10,], [ 5, 15,], [ 10, 14,], [ 3, 1,], [ 11, 13,], [ 12, 13,], [ 0, 5,], [ 9, 11,], [ 10, 12,],]
["10:110"]
alive_cells = [ [ 1, 2,], [ 2, 1,], [ 6, 5,], [ 3, 1,], [ 6, 4,], [ 4, 18,], [ 1, 0,], [ 8, 18,], [ 6, 3,], [ 14, 5,],]
["7:105"]
alive_cells = [ [ 18, 4,], [ 3, 1,], [ 1, 4,], [ 1, 0,], [ 3, 3,], [ 5, 3,], [ 3, 2,],]
["10:126"]
alive_cells = [ [ 11, 7,], [ 8, 8,], [ 7, 7,], [ 8, 7,], [ 0, 9,], [ 10, 6,], [ 8, 6,], [ 5, 19,], [ 12, 5,], [ 9, 7,],]
["9:105"]
alive_cells = [ [ 15, 11,], [ 16, 13,], [ 3, 1,], [ 13, 10,], [ 16, 9,], [ 13, 12,], [ 12, 5,], [ 7, 18,], [ 14, 11,],]
["10:120"]
alive_cells = [ [ 6, 12,], [ 13, 8,], [ 4, 13,], [ 17, 16,], [ 7, 3,], [ 5, 13,], [ 7, 12,], [ 4, 18,], [ 4, 14,], [ 5, 12,],]
["9:106"]
alive_cells = [ [ 15, 5,], [ 2, 4,], [ 13, 1,], [ 19, 17,], [ 16, 4,], [ 7, 3,], [ 15, 3,], [ 14, 2,], [ 13, 5,],]
["9:131"]
alive_cells = [ [ 2, 4,], [ 3, 4,], [ 2, 7,], [ 1, 5,], [ 3, 7,], [ 4, 6,], [ 5, 1,], [ 1, 7,], [ 2, 5,],]
["10:122"]
alive_cells = [ [ 4, 10,], [ 12, 7,], [ 8, 7,], [ 3, 1,], [ 11, 9,], [ 10, 7,], [ 6, 7,], [ 12, 6,], [ 11, 8,], [ 9, 7,],]
["10:118"]
alive_cells = [ [ 10, 15,], [ 4, 19,], [ 9, 2,], [ 7, 3,], [ 9, 15,], [ 3, 19,], [ 9, 14,], [ 17, 11,], [ 9, 17,], [ 8, 15,],]
["10:124"]
alive_cells = [ [ 0, 4,], [ 9, 3,], [ 8, 7,], [ 5, 4,], [ 1, 4,], [ 7, 3,], [ 8, 3,], [ 8, 6,], [ 5, 3,], [ 8, 5,],]
["10:131"]
alive_cells = [ [ 9, 10,], [ 5, 5,], [ 9, 9,], [ 5, 8,], [ 5, 7,], [ 8, 9,], [ 9, 8,], [ 5, 6,], [ 5, 9,], [ 6, 9,],]
